# Provision the Date Generator List

$SharePointSite = "https://powerfxhelp.sharepoint.com/sites/Sandbox"
$ListName = "DateGenerator"

Connect-PnPOnline -url $SharePointSite -Interactive

$CheckExisting =  Get-PnPList -Identity $ListName

If($CheckExisting){

    Remove-PnPList -Identity $ListName -Force

}

# Create List

New-PnPList -Title $ListName -Template GenericList -OnQuickLaunch:$true
Set-PnPList -Identity $ListName -Description "Contains Dates Generated by Date Generator App"

# Add Fields

#Define XML Schema for Date Field
$FieldXML= "<Field Type='DateTime' Name='StartDate' ID='$([GUID]::NewGuid())' DisplayName='Date' Required ='TRUE' Format='DateOnly' FriendlyDisplayFormat='Disabled' Viewable = 'TRUE'></Field>"
#Add DateTime Field to list
Add-PnPFieldFromXml -FieldXml $FieldXML -List $ListName -AddToDefaultView
#Add-PnPField -List $ListName -InternalName "Date" -DisplayName "Date" -Type DateTime -AddToDefaultView
Add-PnPField -List $ListName -InternalName "MonthNum" -DisplayName "MonthNum" -Type Number
Add-PnPField -List $ListName -InternalName "Day" -DisplayName "Day" -Type Number -AddToDefaultView
Add-PnPField -List $ListName -InternalName "Year" -DisplayName "Year" -Type Number -AddToDefaultView
Add-PnPField -List $ListName -InternalName "StartOfWeek" -DisplayName "StartOfWeek" -Type DateTime -AddToDefaultView
Add-PnPField -List $ListName -InternalName "EndOfWeek" -DisplayName "EndOfWeek" -Type DateTime -AddToDefaultView
Add-PnPField -List $ListName -InternalName "ISOWeekNum" -DisplayName "ISOWeekNum" -Type Number -AddToDefaultView
Add-PnPField -List $ListName -InternalName "WkNumDay" -DisplayName "WkNumDay" -Type Text -AddToDefaultView
Add-PnPField -List $ListName -InternalName "WeekdayNum" -DisplayName "WeekdayNum" -Type Number -AddToDefaultView
Add-PnPField -List $ListName -InternalName "isHoliday" -DisplayName "isHoliday" -Type Boolean -AddToDefaultView
Add-PnPField -List $ListName -InternalName "HolidayName" -DisplayName "HolidayName" -Type Text -AddToDefaultView
Add-PnPField -List $ListName -InternalName "isWeekEnd" -DisplayName "isWeekEnd" -Type Boolean -AddToDefaultView

Disconnect-PnPOnline